//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pozicam_web_forms.Appcode.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pozicamskEntities : DbContext
    {
        public pozicamskEntities()
            : base("name=pozicamskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Category_StoreItem> Category_StoreItem { get; set; }
        public virtual DbSet<ManagmentState> ManagmentState { get; set; }
        public virtual DbSet<ManagmentTask> ManagmentTask { get; set; }
        public virtual DbSet<StoreItem> StoreItem { get; set; }
        public virtual DbSet<StoreItem_User_Relations> StoreItem_User_Relations { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
