//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pozicam_web_forms.Appcode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItem_User_Relations
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StoreItemId { get; set; }
    
        public virtual StoreItem StoreItem { get; set; }
        public virtual User User { get; set; }
    }
}
